import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useCallback, useMemo, useState } from 'react';
import { FlatList, Modal, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import PressableView from '@/components/PressableView';
import { ThemedText } from '@/components/ThemedText';
import { useThemeColor } from '@/hooks/useThemeColor';

// Import licenses data - this will be generated by the build-licenses script
// The script removes local paths and includes license text (deduplicated via hashes)
interface LicensesData {
  packages: { packageKey: string; licenses: string; repository?: string; licenseTextHash?: string }[];
  licenseTexts: [string, string][];
}

let licensesData: LicensesData = { packages: [], licenseTexts: [] };
try {
  licensesData = require('../licenses.json');
} catch (error) {
  console.error('licenses.json not found. Run "npm run build-licenses" to generate it.', error);
}

interface LicenseItem {
  packageKey: string;
  packageName: string;
  version: string;
  licenses: string;
  repository?: string;
  licenseTextHash?: string;
}

// Create license texts Map once outside component for better performance
const licenseTextsMap = new Map(licensesData.licenseTexts);

interface LicenseModalItem extends LicenseItem {
  licenseText?: string;
}

export default function LicensesScreen() {
  const insets = useSafeAreaInsets();
  const textColor = useThemeColor({}, 'text');
  const backgroundColor = useThemeColor({}, 'background');
  const cardColor = useThemeColor({}, 'card');
  const tintColor = useThemeColor({}, 'tint');
  const [selectedLicense, setSelectedLicense] = useState<LicenseModalItem | null>(null);

  // Parse packages without resolving license texts (lazy loading)
  const licenseItems: LicenseItem[] = useMemo(() => {
    return licensesData.packages
      .map((packageData) => {
        const match = packageData.packageKey.match(/^(.+)@(.+)$/);
        if (!match) {
          return null;
        }
        const [, packageName, version] = match;

        return {
          packageKey: packageData.packageKey,
          packageName,
          version,
          licenses: packageData.licenses || 'Unknown',
          repository: packageData.repository,
          licenseTextHash: packageData.licenseTextHash,
        } as LicenseItem;
      })
      .filter((item): item is LicenseItem => item !== null)
      .sort((a, b) => a.packageName.localeCompare(b.packageName));
  }, []);

  const handleLicensePress = useCallback((item: LicenseItem) => {
    // Resolve license text only when modal opens (lazy loading)
    const licenseText = item.licenseTextHash ? licenseTextsMap.get(item.licenseTextHash) : undefined;
    setSelectedLicense({
      ...item,
      licenseText,
    });
  }, []);

  const closeModal = () => {
    setSelectedLicense(null);
  };

  const renderLicenseItem = useCallback(
    ({ item }: { item: LicenseItem }) => (
      <PressableView
        onPress={() => handleLicensePress(item)}
        style={[styles.licenseCard, { backgroundColor: cardColor }]}
      >
        <View style={styles.licenseCardContent}>
          <ThemedText type="defaultSemiBold" style={styles.packageName} numberOfLines={1}>
            {item.packageName}
          </ThemedText>
          <ThemedText style={styles.packageVersion}>{item.version}</ThemedText>
          <ThemedText style={[styles.licenseType, { color: tintColor }]}>{item.licenses}</ThemedText>
        </View>
        <Ionicons name="chevron-forward" size={20} color={textColor} style={styles.chevron} />
      </PressableView>
    ),
    [cardColor, textColor, tintColor, handleLicensePress],
  );

  const keyExtractor = useCallback((item: LicenseItem) => `${item.packageName}@${item.version}`, []);

  const renderListHeader = useCallback(
    () => (
      <View>
        <PressableView
          onPress={() => router.push('/sound-licenses')}
          style={[styles.licenseCard, { backgroundColor: cardColor }]}
          accessibilityLabel="Bundled alarm recordings"
        >
          <View style={styles.licenseCardContent}>
            <ThemedText type="defaultSemiBold" style={styles.packageName}>
              Bundled alarm recordings
            </ThemedText>
            <ThemedText style={styles.packageVersion}>
              Public domain, CC0, CC BY-SA, and U.S. government works
            </ThemedText>
          </View>
          <Ionicons name="chevron-forward" size={20} color={textColor} style={styles.chevron} />
        </PressableView>
        <View style={styles.listHeader}>
          <ThemedText type="subtitle">Dependencies licenses</ThemedText>
          <ThemedText style={styles.description}>
            This app uses the following dependency packages. Tap on any dependency to view its license.
          </ThemedText>
        </View>
      </View>
    ),
    [cardColor, textColor],
  );

  const renderListEmpty = useCallback(
    () => (
      <View style={[styles.licenseCard, { backgroundColor: cardColor }]}>
        <ThemedText style={styles.errorText}>No license data found.</ThemedText>
      </View>
    ),
    [cardColor],
  );

  const itemSeparator = useCallback(
    () => <View style={styles.itemSeparator} />,
    [],
  );

  return (
    <View style={[styles.container, { backgroundColor }]}>
      <FlatList
        data={licenseItems}
        renderItem={renderLicenseItem}
        keyExtractor={keyExtractor}
        ListHeaderComponent={renderListHeader}
        ListEmptyComponent={renderListEmpty}
        ItemSeparatorComponent={itemSeparator}
        contentContainerStyle={[
          styles.listContent,
          { paddingBottom: 16 + insets.bottom },
          licenseItems.length === 0 && styles.emptyListContent,
        ]}
        showsVerticalScrollIndicator={false}
        initialNumToRender={20}
        maxToRenderPerBatch={10}
        windowSize={10}
        removeClippedSubviews={true}
      />

      <Modal
        visible={selectedLicense !== null}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={closeModal}
      >
        <View style={[styles.modalContainer, { backgroundColor }]}>
          <View style={[styles.modalHeader, { backgroundColor: cardColor }]}>
            <Pressable onPress={closeModal} style={styles.closeButton}>
              <Ionicons name="close" size={24} color={textColor} />
            </Pressable>
            <ThemedText type="defaultSemiBold" style={styles.modalTitle} numberOfLines={1}>
              {selectedLicense?.packageName}
            </ThemedText>
            <View style={styles.closeButton} />
          </View>
          <ScrollView
            style={styles.modalScrollView}
            contentContainerStyle={styles.modalScrollContent}
            showsVerticalScrollIndicator={true}
          >
            {selectedLicense && (
              <>
                <View style={[styles.modalInfoCard, { backgroundColor: cardColor }]}>
                  <ThemedText style={styles.modalInfoLabel}>Version</ThemedText>
                  <ThemedText style={styles.modalInfoValue}>{selectedLicense.version}</ThemedText>
                </View>
                <View style={[styles.modalInfoCard, { backgroundColor: cardColor }]}>
                  <ThemedText style={styles.modalInfoLabel}>License</ThemedText>
                  <ThemedText style={styles.modalInfoValue}>{selectedLicense.licenses}</ThemedText>
                </View>
                {selectedLicense.repository && (
                  <View style={[styles.modalInfoCard, { backgroundColor: cardColor }]}>
                    <ThemedText style={styles.modalInfoLabel}>Repository</ThemedText>
                    <ThemedText style={styles.modalInfoValue} numberOfLines={2}>
                      {selectedLicense.repository}
                    </ThemedText>
                  </View>
                )}
                {selectedLicense.licenseText ? (
                  <View style={[styles.modalLicenseCard, { backgroundColor: cardColor }]}>
                    <ThemedText type="defaultSemiBold" style={styles.modalLicenseTitle}>
                      License text
                    </ThemedText>
                    <ScrollView
                      style={styles.licenseTextScrollView}
                      contentContainerStyle={styles.licenseTextContent}
                    >
                      <ThemedText style={styles.licenseText}>{selectedLicense.licenseText}</ThemedText>
                    </ScrollView>
                  </View>
                ) : (
                  <View style={[styles.modalLicenseCard, { backgroundColor: cardColor }]}>
                    <ThemedText style={styles.noLicenseText}>
                      License text not available. Please check the package repository for the full license.
                    </ThemedText>
                  </View>
                )}
              </>
            )}
          </ScrollView>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  listContent: {
    padding: 16,
  },
  emptyListContent: {
    flexGrow: 1,
  },
  itemSeparator: {
    height: 12,
  },
  listHeader: {
    gap: 8,
    marginTop: 20,
    marginBottom: 16,
  },
  description: {
    fontSize: 14,
    lineHeight: 20,
  },
  licenseCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 14,
    overflow: 'hidden',
  },
  licenseCardContent: {
    flex: 1,
    gap: 4,
  },
  packageName: {
    fontSize: 16,
    lineHeight: 22,
  },
  packageVersion: {
    fontSize: 12,
    lineHeight: 16,
    opacity: 0.7,
  },
  licenseType: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    marginTop: 2,
  },
  chevron: {
    marginLeft: 8,
    opacity: 0.5,
  },
  errorText: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    padding: 8,
  },
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingTop: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(128, 128, 128, 0.2)',
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: 'bold',
    flex: 1,
    textAlign: 'center',
  },
  modalScrollView: {
    flex: 1,
  },
  modalScrollContent: {
    padding: 16,
    gap: 12,
  },
  modalInfoCard: {
    padding: 16,
    borderRadius: 12,
    gap: 8,
  },
  modalInfoLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    opacity: 0.7,
    textTransform: 'uppercase',
  },
  modalInfoValue: {
    fontSize: 16,
  },
  modalLicenseCard: {
    padding: 16,
    borderRadius: 12,
    minHeight: 200,
  },
  modalLicenseTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  licenseTextScrollView: {
    maxHeight: 400,
  },
  licenseTextContent: {
    padding: 8,
  },
  licenseText: {
    fontSize: 11,
    fontFamily: 'monospace',
    lineHeight: 16,
  },
  noLicenseText: {
    fontSize: 14,
    lineHeight: 20,
    fontStyle: 'italic',
    opacity: 0.7,
  },
});

